# -*- coding: utf-8 -*-
"""AMCS504L Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmbrjfh0G4XMOTs-o8hIdn2sW7ikEf79
"""

import numpy as np
import matplotlib.pyplot as plt

# Part 1
a = 2
b = 4
alph = 110
beta = 0
n = 4

u = {}
v = {}
w = {}

h = (b-a)/n
u[1,0] = alph
u[2,0] = 0
v[1,0] = 0
v[2,0] = 1

for i in range(0,n):
  x = a + i*h
  k11 = h*u[2,i]
  k12 = h*((-2/x)*u[2,i])
  k21 = h*(u[2,i] + 0.5*k12 )
  k22 = h*((-2/(x + h/2))*(u[2,i] + 0.5*k12))
  k31 = h*(u[2,i] + 0.5*k22)
  k32 = h*((-2/(x + h/2))*(u[2,i] + 0.5*k22))
  k41 = h*(u[2,i] + k32)
  k42 = h*((-2/(x + h))*(u[2,i] + k32))

  u[1,i+1] = u[1,i] + (1/6)*(k11 + 2*k21 + 2*k31 + k41)
  u[2,i+1] = u[2,i] + (1/6)*(k12 + 2*k22 + 2*k32 + k42)

  m11 = h*v[2,i]
  m12 = h*((-2/x)*v[2,i] )
  m21 = h*(v[2,i] + 0.5*m12 )
  m22 = h*((-2/(x + h/2))*(v[2,i] + 0.5*m12))
  m31 = h*(v[2,i] + 0.5*m22)
  m32 = h*((-2/(x + h/2))*(v[2,i] + 0.5*m22))
  m41 = h*(v[2,i] + m32)
  m42 = h*((-2/(x + h))*(v[2,i] + m32))
  v[1,i+1] = v[1,i] + (1/6)*(m11 + 2*m21 + 2*m31 + m41)
  v[2,i+1] = v[2,i] + (1/6)*(m12 + 2*m22 + 2*m32 + m42)

w[1,0] = alph
w[2,0] = (beta - u[1,n])/v[1,n]



for i in range(1,n):
  W1 = u[1,i] + w[2,0]*v[1,i]
  W2 = u[2,i] + w[2,0]*v[2,i]
  x  = a + i*h

############################################################################


# Part 2
m = 3
a_1 = np.zeros(m+ 1)
b_1 = np.zeros(m+ 1)
c = np.zeros(m+ 1)
d = np.zeros(m+ 1)
l = np.zeros(m + 1)
u1 = np.zeros(m + 1)
z = np.zeros(m + 1)
w_1 = np.zeros(m + 2)

h1 = (b-a)/(m + 1)
x1 = a + h1
a_1[1] = 2 + h1**2*0
b_1[1] = -1 + (h1/2)*(-2/x1)
d[1] = (1 + (h1/2)*(-2/x1))*alph

for i in range(2, m):
    x1 = a + i*h1
    a_1[i] = 2 + h1**2*0
    b_1[i] = -1 + (h1/2)*(-2/x1)
    c[i] = -1 - (h1/2)*(-2/x1)
    d[i] = -h1**2*0

x1 = b-h1
a_1[m] = 2 + h1**2*0
c[m] = -1 - (h1/2)*(-2/x1)
d[m] = (1 - (h1/2)*(-2/x1))*beta

l[1] = a_1[1]
u1[1] = b_1[1]/a_1[1]
z[1] = d[1]/l[1]

for i in range(2,m):
  l[i] = a_1[i] - c[i]*u1[i-1]
  u1[i] = b_1[i]/l[i]
  z[i] = (d[i] - c[i]*z[i-1])/l[i]

l[m] = a_1[m] - c[m]*u1[m-1]
z[m] = (d[m] - c[m]*z[m-1])/l[m]

w_1[0]=alph
w_1[m+1] = beta
w_1[m] = z[m]

for i in range(m-1, 0, -1):
    w_1[i] = z[i] - u1[i] * w_1[i+1]

for i in range(0,m+1):
  x1 = a +i*h1


print("\nComparison Table")
print(f"{'x':>10} {'Shooting':>15} {'FD':>15} {'Exact':>15} {'Err% (Shoot)':>15} {'Err% (FD)':>15}")
print("-"*90)

for i in range(0, m+1):
    x_val = a + i*h1

    # Shooting
    if i <= n:
        W_shoot = u[1,i] + w[2,0]*v[1,i]
    else:
        W_shoot = float('nan')

    # Finite Difference
    W_fd = w_1[i]

    # Exact
    exact = 110*(a/x_val)*((b-x_val)/(b-a))

    # Percentage errors
    err_shoot = abs((W_shoot - exact)/exact)*100 if exact != 0 else float('nan')
    err_fd = abs((W_fd - exact)/exact)*100 if exact != 0 else float('nan')

    print(f"{x_val:10.4f} "
          f"{W_shoot:15.6f} "
          f"{W_fd:15.6f} "
          f"{exact:15.6f} "
          f"{err_shoot:15.6f} "
          f"{err_fd:15.6f}")

import numpy as np
import matplotlib.pyplot as plt

t_max = 10.0
dt = 0.005
n = int(t_max / dt)


t = np.linspace(0, t_max, n+1)
mu1 = [0, 1, 2]

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 10))


for mu in mu1:

    x1 = np.zeros(n + 1)
    x2 = np.zeros(n + 1)


    x1[0] = 1.0
    x2[0] = 0.0


    for i in range(n):

        curr_x1 = x1[i]
        curr_x2 = x2[i]


        dx1_1 = curr_x2
        dx2_1 = mu * (1 - curr_x1**2) * curr_x2 - curr_x1


        x1_half = curr_x1 + 0.5 * dt * dx1_1
        x2_half = curr_x2 + 0.5 * dt * dx2_1
        dx1_2 = x2_half
        dx2_2 = mu * (1 - x1_half**2) * x2_half - x1_half


        x1_half2 = curr_x1 + 0.5 * dt * dx1_2
        x2_half2 = curr_x2 + 0.5 * dt * dx2_2
        dx1_3 = x2_half2
        dx2_3 = mu * (1 - x1_half2**2) * x2_half2 - x1_half2


        x1_end = curr_x1 + dt * dx1_3
        x2_end = curr_x2 + dt * dx2_3
        dx1_4 = x2_end
        dx2_4 = mu * (1 - x1_end**2) * x2_end - x1_end


        x1[i+1] = curr_x1 + (dt / 6.0) * (dx1_1 + 2*dx1_2 + 2*dx1_3 + dx1_4)
        x2[i+1] = curr_x2 + (dt / 6.0) * (dx2_1 + 2*dx2_2 + 2*dx2_3 + dx2_4)


    ax1.plot(x1, x2, label=f'mu = {mu}')


    ax2.plot(t, x1, label=f'mu = {mu}')


ax1.set_title('Phase Portrait: Velocity vs Position')
ax1.set_xlabel('Position (x)')
ax1.set_ylabel('Velocity (dx/dt)')
ax1.grid(True, linestyle='--', alpha=0.7)
ax1.legend()


ax2.set_title('Solution over Time: Position vs Time')
ax2.set_xlabel('Time (t)')
ax2.set_ylabel('Position (x)')
ax2.grid(True, linestyle='--', alpha=0.7)
ax2.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

t_max = 7.0
dt = 0.001
n = int(t_max / dt)

t = np.linspace(0, t_max, n + 1)
x = np.zeros(n + 1)
y = np.zeros(n + 1)

x[0] = 1000.0
y[0] = 500.0

k1 = 3.0
k2 = 0.0
k3 = 0.002
k4 = -0.5
k5 = -0.0006
k6 = 0.0

for i in range(n):
    curr_x = x[i]
    curr_y = y[i]

    dx1 = curr_x * (k1 - k2 * curr_x - k3 * curr_y)
    dy1 = curr_y * (k4 - k5 * curr_x - k6 * curr_y)

    x_half = curr_x + 0.5 * dt * dx1
    y_half = curr_y + 0.5 * dt * dy1

    dx2 = x_half * (k1 - k2 * x_half - k3 * y_half)
    dy2 = y_half * (k4 - k5 * x_half - k6 * y_half)

    x_half2 = curr_x + 0.5 * dt * dx2
    y_half2 = curr_y + 0.5 * dt * dy2

    dx3 = x_half2 * (k1 - k2 * x_half2 - k3 * y_half2)
    dy3 = y_half2 * (k4 - k5 * x_half2 - k6 * y_half2)

    x_end = curr_x + dt * dx3
    y_end = curr_y + dt * dy3

    dx4 = x_end * (k1 - k2 * x_end - k3 * y_end)
    dy4 = y_end * (k4 - k5 * x_end - k6 * y_end)

    x[i+1] = curr_x + (dt / 6.0) * (dx1 + 2*dx2 + 2*dx3 + dx4)
    y[i+1] = curr_y + (dt / 6.0) * (dy1 + 2*dy2 + 2*dy3 + dy4)

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 10))

ax1.plot(t, x, label='Species x')
ax1.plot(t, y, label='Species y')
ax1.set_title('Population over Time')
ax1.set_xlabel('Time')
ax1.set_ylabel('Population')
ax1.grid(True)
ax1.legend()

ax2.plot(x, y, color='purple')
ax2.set_title('Phase Portrait')
ax2.set_xlabel('Species x')
ax2.set_ylabel('Species y')
ax2.grid(True)

plt.tight_layout()
plt.show()

import numpy as np

t_max = 5.0
dt = 1.0
n = int(t_max / dt)

t = np.linspace(0, t_max, n + 1)
P = np.zeros(n + 1)
P_exact = np.zeros(n + 1)
error = np.zeros(n + 1)

P[0] = 50976.0
b = 2.9e-2
k = 1.4e-7

for i in range(n):
    curr_P = P[i]

    dP1 = curr_P * (b - k * curr_P)

    P_half = curr_P + 0.5 * dt * dP1
    dP2 = P_half * (b - k * P_half)

    P_half2 = curr_P + 0.5 * dt * dP2
    dP3 = P_half2 * (b - k * P_half2)

    P_end = curr_P + dt * dP3
    dP4 = P_end * (b - k * P_end)

    P[i+1] = curr_P + (dt / 6.0) * (dP1 + 2*dP2 + 2*dP3 + dP4)

A = P[0] / (b - k * P[0])

print("Year | Approx Population | Exact Population | Absolute Error")
print("-" * 65)

for i in range(n + 1):
    P_exact[i] = (A * b * np.exp(b * t[i])) / (1 + k * A * np.exp(b * t[i]))
    error[i] = abs(P_exact[i] - P[i])
    print(f"{t[i]:4.0f} | {P[i]:17.5f} | {P_exact[i]:16.5f} | {error[i]:.5e}")